// Code generated by mockery v2.32.0. DO NOT EDIT.

package mocks

import (
	image "image"

	mock "github.com/stretchr/testify/mock"
)

// Sprite is an autogenerated mock type for the Sprite type
type Sprite struct {
	mock.Mock
}

// Set provides a mock function with given fields: visible, cartX, cartY, radianAngle
func (_m *Sprite) Set(visible bool, cartX float64, cartY float64, radianAngle float64) {
	_m.Called(visible, cartX, cartY, radianAngle)
}

// SetPosition provides a mock function with given fields: cartX, cartY
func (_m *Sprite) SetPosition(cartX float64, cartY float64) {
	_m.Called(cartX, cartY)
}

// SetRotation provides a mock function with given fields: radianAngle
func (_m *Sprite) SetRotation(radianAngle float64) {
	_m.Called(radianAngle)
}

// SetScale provides a mock function with given fields: scale
func (_m *Sprite) SetScale(scale float64) {
	_m.Called(scale)
}

// SetSpriteImage provides a mock function with given fields: _a0
func (_m *Sprite) SetSpriteImage(_a0 image.Image) {
	_m.Called(_a0)
}

// SetSpriteImageArrow provides a mock function with given fields:
func (_m *Sprite) SetSpriteImageArrow() {
	_m.Called()
}

// SetSpriteImageTurtle provides a mock function with given fields:
func (_m *Sprite) SetSpriteImageTurtle() {
	_m.Called()
}

// SetVisible provides a mock function with given fields: visible
func (_m *Sprite) SetVisible(visible bool) {
	_m.Called(visible)
}

// NewSprite creates a new instance of Sprite. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSprite(t interface {
	mock.TestingT
	Cleanup(func())
}) *Sprite {
	mock := &Sprite{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
